/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWalletRouteImport } from './routes/_app/wallet'
import { Route as AppTranslatorRouteImport } from './routes/_app/translator'
import { Route as AppTermsRouteImport } from './routes/_app/terms'
import { Route as AppShoppingRouteImport } from './routes/_app/shopping'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppPrivacyRouteImport } from './routes/_app/privacy'
import { Route as AppPremiumRouteImport } from './routes/_app/premium'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppNotesRouteImport } from './routes/_app/notes'
import { Route as AppLanguageRouteImport } from './routes/_app/language'
import { Route as AppHomeRouteImport } from './routes/_app/home'
import { Route as AppHelpRouteImport } from './routes/_app/help'
import { Route as AppExpensesRouteImport } from './routes/_app/expenses'
import { Route as AppDataDeletionRouteImport } from './routes/_app/data-deletion'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppContactsRouteImport } from './routes/_app/contacts'
import { Route as AppConnectRouteImport } from './routes/_app/connect'
import { Route as AppComingSoonRouteImport } from './routes/_app/coming-soon'
import { Route as AppCalendarRouteImport } from './routes/_app/calendar'
import { Route as AppAssistantRouteImport } from './routes/_app/assistant'
import { Route as AppAppointmentsRouteImport } from './routes/_app/appointments'
import { Route as AppAppearanceRouteImport } from './routes/_app/appearance'
import { Route as AppAiMemoryRouteImport } from './routes/_app/ai-memory'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppAboutRouteImport } from './routes/_app/about'
import { Route as AppChatIdRouteImport } from './routes/_app/chat.$id'
import { Route as AppAdminAffiliatesRouteImport } from './routes/_app/admin.affiliates'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const AppTranslatorRoute = AppTranslatorRouteImport.update({
  id: '/translator',
  path: '/translator',
  getParentRoute: () => AppRoute,
} as any)
const AppTermsRoute = AppTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => AppRoute,
} as any)
const AppShoppingRoute = AppShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPrivacyRoute = AppPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AppRoute,
} as any)
const AppPremiumRoute = AppPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRoute,
} as any)
const AppLanguageRoute = AppLanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppDataDeletionRoute = AppDataDeletionRouteImport.update({
  id: '/data-deletion',
  path: '/data-deletion',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsRoute = AppContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectRoute = AppConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => AppRoute,
} as any)
const AppComingSoonRoute = AppComingSoonRouteImport.update({
  id: '/coming-soon',
  path: '/coming-soon',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppAppointmentsRoute = AppAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AppRoute,
} as any)
const AppAppearanceRoute = AppAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => AppRoute,
} as any)
const AppAiMemoryRoute = AppAiMemoryRouteImport.update({
  id: '/ai-memory',
  path: '/ai-memory',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRoute,
} as any)
const AppChatIdRoute = AppChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAffiliatesRoute = AppAdminAffiliatesRouteImport.update({
  id: '/affiliates',
  path: '/affiliates',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/about': typeof AppAboutRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/ai-memory': typeof AppAiMemoryRoute
  '/appearance': typeof AppAppearanceRoute
  '/appointments': typeof AppAppointmentsRoute
  '/assistant': typeof AppAssistantRoute
  '/calendar': typeof AppCalendarRoute
  '/coming-soon': typeof AppComingSoonRoute
  '/connect': typeof AppConnectRoute
  '/contacts': typeof AppContactsRoute
  '/dashboard': typeof AppDashboardRoute
  '/data-deletion': typeof AppDataDeletionRoute
  '/expenses': typeof AppExpensesRoute
  '/help': typeof AppHelpRoute
  '/home': typeof AppHomeRoute
  '/language': typeof AppLanguageRoute
  '/notes': typeof AppNotesRoute
  '/notifications': typeof AppNotificationsRoute
  '/premium': typeof AppPremiumRoute
  '/privacy': typeof AppPrivacyRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/shopping': typeof AppShoppingRoute
  '/terms': typeof AppTermsRoute
  '/translator': typeof AppTranslatorRoute
  '/wallet': typeof AppWalletRoute
  '/admin/affiliates': typeof AppAdminAffiliatesRoute
  '/chat/$id': typeof AppChatIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/about': typeof AppAboutRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/ai-memory': typeof AppAiMemoryRoute
  '/appearance': typeof AppAppearanceRoute
  '/appointments': typeof AppAppointmentsRoute
  '/assistant': typeof AppAssistantRoute
  '/calendar': typeof AppCalendarRoute
  '/coming-soon': typeof AppComingSoonRoute
  '/connect': typeof AppConnectRoute
  '/contacts': typeof AppContactsRoute
  '/dashboard': typeof AppDashboardRoute
  '/data-deletion': typeof AppDataDeletionRoute
  '/expenses': typeof AppExpensesRoute
  '/help': typeof AppHelpRoute
  '/home': typeof AppHomeRoute
  '/language': typeof AppLanguageRoute
  '/notes': typeof AppNotesRoute
  '/notifications': typeof AppNotificationsRoute
  '/premium': typeof AppPremiumRoute
  '/privacy': typeof AppPrivacyRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/shopping': typeof AppShoppingRoute
  '/terms': typeof AppTermsRoute
  '/translator': typeof AppTranslatorRoute
  '/wallet': typeof AppWalletRoute
  '/admin/affiliates': typeof AppAdminAffiliatesRoute
  '/chat/$id': typeof AppChatIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_app/about': typeof AppAboutRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/ai-memory': typeof AppAiMemoryRoute
  '/_app/appearance': typeof AppAppearanceRoute
  '/_app/appointments': typeof AppAppointmentsRoute
  '/_app/assistant': typeof AppAssistantRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/coming-soon': typeof AppComingSoonRoute
  '/_app/connect': typeof AppConnectRoute
  '/_app/contacts': typeof AppContactsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/data-deletion': typeof AppDataDeletionRoute
  '/_app/expenses': typeof AppExpensesRoute
  '/_app/help': typeof AppHelpRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/language': typeof AppLanguageRoute
  '/_app/notes': typeof AppNotesRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/premium': typeof AppPremiumRoute
  '/_app/privacy': typeof AppPrivacyRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/shopping': typeof AppShoppingRoute
  '/_app/terms': typeof AppTermsRoute
  '/_app/translator': typeof AppTranslatorRoute
  '/_app/wallet': typeof AppWalletRoute
  '/_app/admin/affiliates': typeof AppAdminAffiliatesRoute
  '/_app/chat/$id': typeof AppChatIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/about'
    | '/admin'
    | '/ai-memory'
    | '/appearance'
    | '/appointments'
    | '/assistant'
    | '/calendar'
    | '/coming-soon'
    | '/connect'
    | '/contacts'
    | '/dashboard'
    | '/data-deletion'
    | '/expenses'
    | '/help'
    | '/home'
    | '/language'
    | '/notes'
    | '/notifications'
    | '/premium'
    | '/privacy'
    | '/profile'
    | '/settings'
    | '/shopping'
    | '/terms'
    | '/translator'
    | '/wallet'
    | '/admin/affiliates'
    | '/chat/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/about'
    | '/admin'
    | '/ai-memory'
    | '/appearance'
    | '/appointments'
    | '/assistant'
    | '/calendar'
    | '/coming-soon'
    | '/connect'
    | '/contacts'
    | '/dashboard'
    | '/data-deletion'
    | '/expenses'
    | '/help'
    | '/home'
    | '/language'
    | '/notes'
    | '/notifications'
    | '/premium'
    | '/privacy'
    | '/profile'
    | '/settings'
    | '/shopping'
    | '/terms'
    | '/translator'
    | '/wallet'
    | '/admin/affiliates'
    | '/chat/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_app/about'
    | '/_app/admin'
    | '/_app/ai-memory'
    | '/_app/appearance'
    | '/_app/appointments'
    | '/_app/assistant'
    | '/_app/calendar'
    | '/_app/coming-soon'
    | '/_app/connect'
    | '/_app/contacts'
    | '/_app/dashboard'
    | '/_app/data-deletion'
    | '/_app/expenses'
    | '/_app/help'
    | '/_app/home'
    | '/_app/language'
    | '/_app/notes'
    | '/_app/notifications'
    | '/_app/premium'
    | '/_app/privacy'
    | '/_app/profile'
    | '/_app/settings'
    | '/_app/shopping'
    | '/_app/terms'
    | '/_app/translator'
    | '/_app/wallet'
    | '/_app/admin/affiliates'
    | '/_app/chat/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/wallet': {
      id: '/_app/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/translator': {
      id: '/_app/translator'
      path: '/translator'
      fullPath: '/translator'
      preLoaderRoute: typeof AppTranslatorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/terms': {
      id: '/_app/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof AppTermsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shopping': {
      id: '/_app/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof AppShoppingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/privacy': {
      id: '/_app/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof AppPrivacyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/premium': {
      id: '/_app/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof AppPremiumRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notes': {
      id: '/_app/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/language': {
      id: '/_app/language'
      path: '/language'
      fullPath: '/language'
      preLoaderRoute: typeof AppLanguageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/help': {
      id: '/_app/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses': {
      id: '/_app/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/data-deletion': {
      id: '/_app/data-deletion'
      path: '/data-deletion'
      fullPath: '/data-deletion'
      preLoaderRoute: typeof AppDataDeletionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts': {
      id: '/_app/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AppContactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connect': {
      id: '/_app/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof AppConnectRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/coming-soon': {
      id: '/_app/coming-soon'
      path: '/coming-soon'
      fullPath: '/coming-soon'
      preLoaderRoute: typeof AppComingSoonRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assistant': {
      id: '/_app/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/appointments': {
      id: '/_app/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppAppointmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/appearance': {
      id: '/_app/appearance'
      path: '/appearance'
      fullPath: '/appearance'
      preLoaderRoute: typeof AppAppearanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-memory': {
      id: '/_app/ai-memory'
      path: '/ai-memory'
      fullPath: '/ai-memory'
      preLoaderRoute: typeof AppAiMemoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/about': {
      id: '/_app/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat/$id': {
      id: '/_app/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof AppChatIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/affiliates': {
      id: '/_app/admin/affiliates'
      path: '/affiliates'
      fullPath: '/admin/affiliates'
      preLoaderRoute: typeof AppAdminAffiliatesRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminAffiliatesRoute: typeof AppAdminAffiliatesRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAffiliatesRoute: AppAdminAffiliatesRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAboutRoute: typeof AppAboutRoute
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppAiMemoryRoute: typeof AppAiMemoryRoute
  AppAppearanceRoute: typeof AppAppearanceRoute
  AppAppointmentsRoute: typeof AppAppointmentsRoute
  AppAssistantRoute: typeof AppAssistantRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppComingSoonRoute: typeof AppComingSoonRoute
  AppConnectRoute: typeof AppConnectRoute
  AppContactsRoute: typeof AppContactsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDataDeletionRoute: typeof AppDataDeletionRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppHelpRoute: typeof AppHelpRoute
  AppHomeRoute: typeof AppHomeRoute
  AppLanguageRoute: typeof AppLanguageRoute
  AppNotesRoute: typeof AppNotesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPremiumRoute: typeof AppPremiumRoute
  AppPrivacyRoute: typeof AppPrivacyRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppShoppingRoute: typeof AppShoppingRoute
  AppTermsRoute: typeof AppTermsRoute
  AppTranslatorRoute: typeof AppTranslatorRoute
  AppWalletRoute: typeof AppWalletRoute
  AppChatIdRoute: typeof AppChatIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAboutRoute: AppAboutRoute,
  AppAdminRoute: AppAdminRouteWithChildren,
  AppAiMemoryRoute: AppAiMemoryRoute,
  AppAppearanceRoute: AppAppearanceRoute,
  AppAppointmentsRoute: AppAppointmentsRoute,
  AppAssistantRoute: AppAssistantRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppComingSoonRoute: AppComingSoonRoute,
  AppConnectRoute: AppConnectRoute,
  AppContactsRoute: AppContactsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDataDeletionRoute: AppDataDeletionRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppHelpRoute: AppHelpRoute,
  AppHomeRoute: AppHomeRoute,
  AppLanguageRoute: AppLanguageRoute,
  AppNotesRoute: AppNotesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPremiumRoute: AppPremiumRoute,
  AppPrivacyRoute: AppPrivacyRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppShoppingRoute: AppShoppingRoute,
  AppTermsRoute: AppTermsRoute,
  AppTranslatorRoute: AppTranslatorRoute,
  AppWalletRoute: AppWalletRoute,
  AppChatIdRoute: AppChatIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
